- name: Remove any previous versions of docker that might come bundled on the system
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add Docker signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    id: 0EBFCD88

- name: Set up stable repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu "{{ ansible_distribution_release }}" stable
    state: present

- name: Update the package index
  apt:
    update_cache: yes

- name: Install the latest version of Docker CE and containerd
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Configure remote access with daemon.json by copying file to /etc/docker/daemon.json
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Create directory for systemd docker.conf file
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory
    mode: 0775

- name: Configure the systemctl file
  copy:
    src: docker.conf
    dest: /etc/systemd/system/docker.service.d/docker.conf

- name: Reload system control daemon(necessary for changes to docker.conf and daemon.json to take effect)
  command: systemctl daemon-reload

- name: Restart docker
  service:
    name: docker
    state: restarted
